name: Latest blog post workflow
on:
  workflow_dispatch:
  schedule:
    # Runs at 2am UTC
    - cron: '0 2 * * *'

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/brennan,https://brennanbrown.github.io/old-blog/feed"
